trigger:
- main

pool:
 name: 'Agent-Self-Hosted'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureRM-Service'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --name MyResourceGroup --location eastus'
    failOnStandardError: true

    
