trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureRM-Service'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --resource-group 'Your-Resource-Group' --template-file azuredeploy.json
    failOnStandardError: true

    
